### PR TITLE
High dpi window position/size fix

### LINKED ISSUE #333: Dual Monitor high dpi window sizes and positions broken
I work primarily on a dual monitor (2x 4K) setup.
Every second time I start snoop it is out of screen (need to close it via taskbar) and the next time the position is just somewhere.
Also the window sizes of the snoop windows are way way too big.
Probably snoop wants to set it's last position/size but without accounting for high dpi.

Not a breaking issue, just a bit annoying :)

### PR DESCRIPTION
**Pull request by Algorithman**
Fixes #333

### CODE REVIEW

**Comment by batzen** [comment]
Will try to have a look tomorrow as i am busy today.

**Comment by Algorithman** [comment]
No worries :) It is Saturday after all.

**Comment by batzen** [comment]
Thanks for contributing!

**Comment by Algorithman** [comment]
You're welcome.

Only the lack of a credit card/paypal account stops me from sponsoring you. Do you have any other payment method? Wanted to give you 50€...

**Comment by batzen** [comment]
If you send me an e-mail or DM me on twitter/gitter i can give you my IBAN. ;-)

**Comment by Algorithman** [comment]
You got mail :)

**Pull request merged**
